##################################################
# Statistical Analysis of Dinos ARN editing Data # @Name of the article
##################################################

#  Created by Lucas Paoli. Contact : lucas.paoli@ens.fr | lucas.paoli@gmail.com
#  On OS X 10.9.5 - x86_64, darwin13.4.0
#  R version 3.3.1 (2016-06-21)

# Notation :
# We focus on 4 organisms 
# kv : K. veneficum / Fucoxanthin
# km : K. mikimotoi / Fucoxanthin
# sm : S. minutum / Peridinin
# pl : P. lunula / Peridinin

###########################
# SLIDING WINDOW ANALYSIS #
###########################

library(car)
library(lsmeans)
library(nlme)
library(lme4)
library(multcomp)
library(lmerTest)
library(MuMIn)

################
# Loading data #
################

SW=read.delim(file="../DATA/SW_analysis_global_lucas.csv",sep=",")

# Filtering out p-value < 0.05
SW=subset(SW,dt(SW$amino_acid_t_value,df=SW$DF_.N.2.)<=0.05)

# Loading the edit score data : goal is to investigate relationship between SW and edit score
table=read.delim(file="../DATA/table_analysis_global_lucas.csv",sep=",")

#Gene as character to avoid potential issues
SW$gene=as.character(SW$gene)
table$gene=as.character(table$gene)

# Adding the pearson correlation to the table with edit scores
for (i in 1:nrow(table)){
  if (length(subset(SW, gene == table[i,"gene"] &
                      organism == table[i,"organism"] &
                      reference == table[i,"reference"])$amino_acid_pearson_correlation)==0){
    table[i,8]=NA
  }else{
    table[i,8]=subset(SW, gene == table[i,"gene"] &
                            organism == table[i,"organism"] &
                            reference == table[i,"reference"])$amino_acid_pearson_correlation
  }
}

table=na.omit(table)
names(table)=c(names(table)[-8],"SW.score")

attach(table)

View(table) # Inspecting the Data

#########
# Stats #
#########

# "Reference" causes dependance in the data
# We ought to investigate this effect using a mixed model

# Complete model, with all potential effects
SW.lmer1=lmer(SW.score~average.edit.score.diff+num.AA.changes+gene_family+plastid+reference+
                gene_family*plastid+plastid*reference+average.edit.score.diff*plastid+average.edit.score.diff*reference+
                   (1|gene),REML=F)
summary(SW.lmer1)
Anova(SW.lmer1)
step(SW.lmer1)

# Using the model generated by step
SW.lmer0=lmer(formula = SW.score ~ gene_family + plastid + 
                (1|gene) + gene_family:plastid, REML = F, 
              contrasts = list(gene_family = "contr.SAS", plastid = "contr.SAS"))

# Step model as significant as the complete one :

anova(SW.lmer1,SW.lmer0)

# Effects significance :
Anova(SW.lmer0)

# Addind reference, base on lmer1 summary
SW.lmer=lmer(formula = SW.score ~ gene_family + plastid + reference + 
               (1 | gene) + gene_family:plastid, REML = F)

# lmer0 is more meaningfull
anova(SW.lmer,SW.lmer0)

summary(SW.lmer)
Anova(SW.lmer)
anova(SW.lmer)

# Validation of the model
plot(SW.lmer0)


table(plastid,gene_family) # Contingence table

# Mean comparison, using lsmeans and glht 
# to perform the tests using Tukey post hoc tests.
lsmeans(SW.lmer0)
summary(glht(SW.lmer0,linfct=mcp(plastid="Tukey")))
summary(glht(SW.lmer0,linfct=mcp(gene_family="Tukey")))
summary(glht(SW.lmer,linfct=mcp(reference="Tukey")))

r.squaredGLMM(SW.lmer)
r.squaredGLMM(SW.lmer0)

# Investigating potential organism effects. As plastid is a linear combinaison of organism, this is a different model.
#########################

# Complete model, with all potential effects
org.lmer1=lmer(SW.score~average.edit.score.diff+num.AA.changes+gene_family+organism+reference+
                 gene_family*organism+organism*reference+average.edit.score.diff*organism+average.edit.score.diff*reference+
                 (1|gene),REML=F)
summary(org.lmer1)
Anova(org.lmer1)
step(org.lmer1)

# Using the model generated by step
org.lmer0=lmer(formula = SW.score ~ average.edit.score.diff + gene_family + 
                 organism + reference + (1 | gene) + gene_family:organism + 
                 average.edit.score.diff:organism, REML = F, contrasts = list(
                   gene_family = "contr.SAS", organism = "contr.SAS", reference = "contr.SAS"))

# Step model as significant as the complete one :

anova(org.lmer1,org.lmer0)

# Effects significance :
Anova(org.lmer0)

# Simplifying the model
org.lmer=lmer(formula = SW.score ~ gene_family + organism + 
                (1 | gene) + gene_family:organism, REML = F)

# lmer0 is more meaningfull
anova(org.lmer,org.lmer0)

summary(org.lmer)
Anova(org.lmer)
anova(org.lmer)

# Validation of the model
plot(org.lmer0)


table(organism,gene_family) # Contingence table

# Mean comparison, using lsmeans and glht 
# to perform the tests using Tukey post hoc tests.
lsmeans(org.lmer0)
summary(glht(org.lmer0,linfct=mcp(organism="Tukey")))
summary(glht(org.lmer0,linfct=mcp(gene_family="Tukey")))
summary(glht(org.lmer0,linfct=mcp(reference="Tukey")))

r.squaredGLMM(org.lmer)
r.squaredGLMM(org.lmer0)
